First implementation
MiroJoseph01/FileVisitorTask pull request #1
Opened 2021-03-19 14:34 UTC by MiroJoseph01

2021-03-19 15:39 UTC, bugaiov-vs requested changes

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/FileSystemVisitor.cs
> +        private Func<string, bool> _func;
Unused variable, try to keep your project as clean as possible.

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/FileSystemVisitor.cs
> +                _ioWrapper.CreateDirectory(directory);
I think we need to finish our function if the origin directory not found.

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/FileSystemVisitor.cs
> +            string currentDirName = _ioWrapper.GetCurrentDirectory();
These two just write and then read, not looks cool together.

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/FileSystemVisitor.cs
> +            {
We twice run over the `result` collection, it's ok if we have 100 files or directories, but what about 1.000.000, it will take time. I would combine them, but I think you are not gonna need it after the implementation of the "true iterator"

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/IOWrapper.cs
> +            System.IO.Directory.CreateDirectory(directory);
Let's replace all occurrences System.IO. with only one line using System.IO. it will reduce duplications

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/Program.cs
>          static void Main(string[] args)
It's up to you to play with args or not. I won't reduce the score for it

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/Program.cs
> +                }
The first if condition looks redundant.

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/Program.cs
> +                if (searParams.SkipCondition(value.Value) && searParams.StopCondition(value.Value))
Let's create closure here and remove a redundant parameter, we can change `searParams` to `searchParams` from line:32.

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/FileSystemVisitor.cs
> +                files = _ioWrapper.GetFiles(root, @"*.*");
Our string doesn't have some literals (\t, \n etc.) that could be escaped

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/FileSystemVisitor.cs
> +            Notify?.Invoke($"\nFinish");
We don't need interpolation here, no inline parameters

2021-03-19 15:39 UTC, bugaiov-vs commented on FileVisitor/FileSystemVisitor.cs
> +            }
Just FYI: there is a super feature in C# 8, one line `result ??= new FileIterator();` but does the same.
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#null-coalescing-assignment

2021-03-19 15:51 UTC, bugaiov-vs requested changes

2021-03-19 15:51 UTC, bugaiov-vs commented on FileVisitor/Program.cs
> +            FileVisitorTask.Search += (value, searParams) =>
Try to test: We use here return in our lambda-listener to return Search result, what if we will have more than one listener with a return statement, what value we will be returned from Search.Invoke() ?

2021-03-21 06:43 UTC, MiroJoseph01 commented on FileVisitor/Program.cs
> +                }
If you don't mind, I'll write 'done' to highlight what I've done

2021-03-21 06:43 UTC, MiroJoseph01 commented on FileVisitor/Program.cs
> +                }
Done

2021-03-21 06:55 UTC, MiroJoseph01 commented on FileVisitor/Entities/File.cs
> +    public class File : IEntity
done

2021-03-21 06:55 UTC, MiroJoseph01 commented on FileVisitor/Entities/Directory.cs
> +    public class Directory : IEntity
done

2021-03-21 06:55 UTC, MiroJoseph01 commented on FileVisitor/FileSystemVisitor.cs
> +        private Func<string, bool> _func;
done

2021-03-21 07:21 UTC, MiroJoseph01 commented on FileVisitor/FileSystemVisitor.cs
> +            {
done

2021-03-21 07:22 UTC, MiroJoseph01 commented on FileVisitor/IOWrapper.cs
> +            System.IO.Directory.CreateDirectory(directory);
done

2021-03-21 07:22 UTC, MiroJoseph01 commented on FileVisitor/Program.cs
> +                if (searParams.SkipCondition(value.Value) && searParams.StopCondition(value.Value))
done

2021-03-21 07:25 UTC, MiroJoseph01 commented on FileVisitor/FileSystemVisitor.cs
> +            Notify?.Invoke($"\nFinish");
done

2021-03-21 07:26 UTC, MiroJoseph01 commented on FileVisitor/FileSystemVisitor.cs
> +            }
thanks for the tip)

2021-03-21 07:32 UTC, MiroJoseph01 commented on FileVisitor/FileItertator.cs
> +    public class FileItertator : IEnumerable<IEntity>
done

2021-03-21 07:32 UTC, MiroJoseph01 commented on FileVisitor/FileSystemVisitor.cs
> +                _ioWrapper.CreateDirectory(directory);
done

2021-03-21 07:32 UTC, MiroJoseph01 commented on FileVisitor/FileSystemVisitor.cs
> +            string currentDirName = _ioWrapper.GetCurrentDirectory();
done

2021-03-21 07:34 UTC, MiroJoseph01 commented on FileVisitor/FileSystemVisitor.cs
> +                files = _ioWrapper.GetFiles(root, @"*.*");
Sorry, I don't understand fully what you meant

2021-03-21 07:43 UTC, MiroJoseph01 commented on FileVisitor/FileSystemVisitor.cs
> +                files = _ioWrapper.GetFiles(root, @"*.*");
You mean I should remove `@` before the string, shouldn't I?

2021-03-21 07:58 UTC, MiroJoseph01 commented on FileVisitor/Program.cs
> +            FileVisitorTask.Search += (value, searParams) =>
return only second listener result

2021-03-21 21:21 UTC, bugaiov-vs requested changes

2021-03-21 21:21 UTC, bugaiov-vs commented on FileVisitor/Entities/Entity.cs
> +                if (Type == EntityType.File) { return GetFileNameWithoutPath(_value); }
Nice decision to keep your own logic.

One note. We already have an implementation from the box. Try to use as much as possible from the box due to new code = new possible bugs and more logic which requires maintance.


Check https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfilenamewithoutextension?view=net-5.0

2021-03-21 21:21 UTC, bugaiov-vs commented on FileVisitor/Entities/SearchResult.cs
> +        Skip,
Just a recommendation. 
Try always to put the first enum's item as `None` or `Unknown ` = 0.
Because if we will forget somewhere to init it would be set as default and equals 0 that cause our program to `Skip` but `None` wouldn't make any logic based on special values.

Skip it for this task if u want, but please try to follow this rule in future tasks.

2021-03-21 21:21 UTC, bugaiov-vs commented on FileVisitor/FileItertator.cs
> +                foreach (var f in files)
Good job. It looks like a true iterator.

Just recomendation: use `singular` in `plural ` e.g. `file in files`.
Skip it for this task if u want, but please try to follow this rule in future tasks.

2021-03-21 21:29 UTC, bugaiov-vs commented on FileVisitor/FileSystemVisitor.cs
> +                files = _ioWrapper.GetFiles(root, @"*.*");
Yes, @ used only to escape literals like \t \r \n etc. there aren't such things.

2021-03-22 06:54 UTC, MiroJoseph01 commented on FileVisitor/Entities/Entity.cs
> +                if (Type == EntityType.File) { return GetFileNameWithoutPath(_value); }
didn't know, thank you
done

2021-03-22 11:48 UTC, bugaiov-vs approved these changes

2021-03-22 15:36 UTC, merged